# Uncomment the next line to define a global platform for your project
# platform :ios, '10.0'

target 'CarPool' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'GoogleMaps', '~> 2.6.0' 
  pod 'Toast-Swift', '~> 5.0.0'
	pod 'Fabric'
	pod 'Crashlytics'
  # Pods for CarPool

end
